version: '3.9'

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - uploads:/app/uploads
      - temp_audio:/app/temp_audio
      - logs:/app/logs
    env_file:
      - .env.prod
    environment:
      - PYTHONUNBUFFERED=1
      # Using Flask 2.3+ compatible env vars
      - FLASK_DEBUG=0
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health | grep -q '\"status\":\"healthy\"'"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

volumes:
  uploads:
    driver: local
  temp_audio:
    driver: local
  logs:
    driver: local
